name: dan-plugin-arbt

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/*.yml'
  workflow_dispatch:

env:
  FUNCTION_PROJECT_PATH: src/Altinn.Dan.Plugin.Arbeidstilsynet

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Get the latest source code'
        uses: actions/checkout@v2

      - name: 'Build, test and upload artifact'
        uses: Altinn/dan-deploy-actions/composite/build@feature/composite-actions
        with:
          azure_artifact_pat: ${{ secrets.AZURE_ARTIFACTS_PAT }}
          function_project_path: ${{ env.FUNCTION_PROJECT_PATH }}
          upload: true

  deploy-dev:
    runs-on: ubuntu-latest
    environment: 'dev'
    needs: build-and-publish
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy to dev'
        uses: Altinn/dan-deploy-actions/composite/deploy@feature/composite-actions
        with:
          function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
          publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}

  deploy-staging:
    runs-on: ubuntu-latest
    environment: 'staging'
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy to staging'
        uses: Altinn/dan-deploy-actions/composite/deploy@feature/composite-actions
        with:
          function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
          publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}

  swap-staging-production:
    runs-on: ubuntu-latest
    environment: 'production'
    needs: deploy-staging
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Swap staging and production'
        run: |
          az webapp deployment slot swap -g '${{ env.RESOURCE_GROUP_PROD }}' -n '${{ secrets.FUNCTIONAPP_NAME }}' --slot 'staging' --target-slot 'production'
      - name: 'Azure logout'
        run: |
          az logout

  redeploy-staging:
    runs-on: ubuntu-latest
    environment: 'staging'
    needs: swap-staging-production
    steps:
      - uses: actions/checkout@v2
      - name: 'Redeploy to staging'
        uses: Altinn/dan-deploy-actions/composite/deploy@feature/composite-actions
        with:
          function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
          publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
