name: Experiment on reusable workflows

on:
  workflow_dispatch:

env:
  FUNCTION_PROJECT_PATH: 'src/Altinn.Dan.Plugin.Arbeidstilsynet'

jobs:
  run:
    uses: Altinn/dan-deploy-actions/.github/workflows/dan-deploy-flow.yml@main
    with:
      artifact_name: 'dan-plugin-arbt'
      function_project_path: ${{ env.FUNCTION_PROJECT_PATH }}
    secrets:
      function_app_name: ${{ secrets.FUNCTIONAPP_NAME }}
      publish_profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
      azure_artifact_pat: ${{ secrets.AZURE_ARTIFACTS_PAT }}

