name: Build & test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/*.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ROOT_SOLUTION_PATH: ./
  AZURE_FUNCTIONAPP_NAME: func-esarbt-test-dev # set this to the name of your azure function app resource
  AZURE_FUNCTION_PROJ_PATH: src/Altinn.Dan.Plugin.Arbeidstilsynet  # set this to the path to your function app project
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/nadobe/Nadobe/_packaging/Packages/nuget/v3/index.json
  BUILD_CONFIGURATION: 'Release'    # set this to the appropriate build configuration
  DOTNET_VERSION: '6.0.x' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the latest source code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.AZURE_ARTIFACTS_PAT }}

      - name: Restore, build & test
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal
        working-directory: ${{ env.ROOT_SOLUTION_PATH }}

      - name: Build Function App for Release
        run: dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}' --output ./output
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTION_PROJ_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
